#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DATAGAMESTORE")]
	public partial class DataGameStoreDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertADMIN(ADMIN instance);
    partial void UpdateADMIN(ADMIN instance);
    partial void DeleteADMIN(ADMIN instance);
    partial void InsertTINNHAN(TINNHAN instance);
    partial void UpdateTINNHAN(TINNHAN instance);
    partial void DeleteTINNHAN(TINNHAN instance);
    partial void InsertBAIDANGCONGDONG(BAIDANGCONGDONG instance);
    partial void UpdateBAIDANGCONGDONG(BAIDANGCONGDONG instance);
    partial void DeleteBAIDANGCONGDONG(BAIDANGCONGDONG instance);
    partial void InsertDANHGIA(DANHGIA instance);
    partial void UpdateDANHGIA(DANHGIA instance);
    partial void DeleteDANHGIA(DANHGIA instance);
    partial void InsertDANHGIACONGDONG(DANHGIACONGDONG instance);
    partial void UpdateDANHGIACONGDONG(DANHGIACONGDONG instance);
    partial void DeleteDANHGIACONGDONG(DANHGIACONGDONG instance);
    partial void InsertDONHANG(DONHANG instance);
    partial void UpdateDONHANG(DONHANG instance);
    partial void DeleteDONHANG(DONHANG instance);
    partial void InsertGAME_THELOAI(GAME_THELOAI instance);
    partial void UpdateGAME_THELOAI(GAME_THELOAI instance);
    partial void DeleteGAME_THELOAI(GAME_THELOAI instance);
    partial void InsertGAME(GAME instance);
    partial void UpdateGAME(GAME instance);
    partial void DeleteGAME(GAME instance);
    partial void InsertKETBAN(KETBAN instance);
    partial void UpdateKETBAN(KETBAN instance);
    partial void DeleteKETBAN(KETBAN instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertNHAPHATHANH(NHAPHATHANH instance);
    partial void UpdateNHAPHATHANH(NHAPHATHANH instance);
    partial void DeleteNHAPHATHANH(NHAPHATHANH instance);
    partial void InsertNHAPHATTRIEN(NHAPHATTRIEN instance);
    partial void UpdateNHAPHATTRIEN(NHAPHATTRIEN instance);
    partial void DeleteNHAPHATTRIEN(NHAPHATTRIEN instance);
    partial void InsertQUOCGIA(QUOCGIA instance);
    partial void UpdateQUOCGIA(QUOCGIA instance);
    partial void DeleteQUOCGIA(QUOCGIA instance);
    partial void InsertTHELOAI(THELOAI instance);
    partial void UpdateTHELOAI(THELOAI instance);
    partial void DeleteTHELOAI(THELOAI instance);
    partial void InsertKETBAN1(KETBAN1 instance);
    partial void UpdateKETBAN1(KETBAN1 instance);
    partial void DeleteKETBAN1(KETBAN1 instance);
    #endregion
		
		public DataGameStoreDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DATAGAMESTOREConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataGameStoreDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataGameStoreDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataGameStoreDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataGameStoreDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADMIN> ADMINs
		{
			get
			{
				return this.GetTable<ADMIN>();
			}
		}
		
		public System.Data.Linq.Table<TINNHAN> TINNHANs
		{
			get
			{
				return this.GetTable<TINNHAN>();
			}
		}
		
		public System.Data.Linq.Table<ANN> ANNs
		{
			get
			{
				return this.GetTable<ANN>();
			}
		}
		
		public System.Data.Linq.Table<BAIDANGCONGDONG> BAIDANGCONGDONGs
		{
			get
			{
				return this.GetTable<BAIDANGCONGDONG>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETDONHANG> CHITIETDONHANGs
		{
			get
			{
				return this.GetTable<CHITIETDONHANG>();
			}
		}
		
		public System.Data.Linq.Table<DANHGIA> DANHGIAs
		{
			get
			{
				return this.GetTable<DANHGIA>();
			}
		}
		
		public System.Data.Linq.Table<DANHGIACONGDONG> DANHGIACONGDONGs
		{
			get
			{
				return this.GetTable<DANHGIACONGDONG>();
			}
		}
		
		public System.Data.Linq.Table<DONHANG> DONHANGs
		{
			get
			{
				return this.GetTable<DONHANG>();
			}
		}
		
		public System.Data.Linq.Table<GAME_THELOAI> GAME_THELOAIs
		{
			get
			{
				return this.GetTable<GAME_THELOAI>();
			}
		}
		
		public System.Data.Linq.Table<GAME> GAMEs
		{
			get
			{
				return this.GetTable<GAME>();
			}
		}
		
		public System.Data.Linq.Table<KETBAN> KETBANs
		{
			get
			{
				return this.GetTable<KETBAN>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<NHAPHATHANH> NHAPHATHANHs
		{
			get
			{
				return this.GetTable<NHAPHATHANH>();
			}
		}
		
		public System.Data.Linq.Table<NHAPHATTRIEN> NHAPHATTRIENs
		{
			get
			{
				return this.GetTable<NHAPHATTRIEN>();
			}
		}
		
		public System.Data.Linq.Table<PTTHANHTOAN> PTTHANHTOANs
		{
			get
			{
				return this.GetTable<PTTHANHTOAN>();
			}
		}
		
		public System.Data.Linq.Table<QUOCGIA> QUOCGIAs
		{
			get
			{
				return this.GetTable<QUOCGIA>();
			}
		}
		
		public System.Data.Linq.Table<THELOAI> THELOAIs
		{
			get
			{
				return this.GetTable<THELOAI>();
			}
		}
		
		public System.Data.Linq.Table<KETBAN1> KETBAN1s
		{
			get
			{
				return this.GetTable<KETBAN1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN")]
	public partial class ADMIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaAd;
		
		private string _HoTen;
		
		private string _DienThoai;
		
		private string _Email;
		
		private string _TenDN;
		
		private string _MatKhau;
		
		private System.Nullable<int> _Quyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaAdChanging(int value);
    partial void OnMaAdChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTenDNChanging(string value);
    partial void OnTenDNChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnQuyenChanging(System.Nullable<int> value);
    partial void OnQuyenChanged();
    #endregion
		
		public ADMIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaAd", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaAd
		{
			get
			{
				return this._MaAd;
			}
			set
			{
				if ((this._MaAd != value))
				{
					this.OnMaAdChanging(value);
					this.SendPropertyChanging();
					this._MaAd = value;
					this.SendPropertyChanged("MaAd");
					this.OnMaAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(10)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDN", DbType="VarChar(15)")]
		public string TenDN
		{
			get
			{
				return this._TenDN;
			}
			set
			{
				if ((this._TenDN != value))
				{
					this.OnTenDNChanging(value);
					this.SendPropertyChanging();
					this._TenDN = value;
					this.SendPropertyChanged("TenDN");
					this.OnTenDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(15)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="Int")]
		public System.Nullable<int> Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this.OnQuyenChanging(value);
					this.SendPropertyChanging();
					this._Quyen = value;
					this.SendPropertyChanged("Quyen");
					this.OnQuyenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TINNHAN")]
	public partial class TINNHAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_TinNhan;
		
		private System.Nullable<int> _Id_NguoiGui;
		
		private System.Nullable<int> _Id_NguoiNhan;
		
		private string _NoiDung;
		
		private System.Nullable<System.DateTime> _NgayGui;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_TinNhanChanging(int value);
    partial void OnId_TinNhanChanged();
    partial void OnId_NguoiGuiChanging(System.Nullable<int> value);
    partial void OnId_NguoiGuiChanged();
    partial void OnId_NguoiNhanChanging(System.Nullable<int> value);
    partial void OnId_NguoiNhanChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnNgayGuiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGuiChanged();
    #endregion
		
		public TINNHAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_TinNhan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_TinNhan
		{
			get
			{
				return this._Id_TinNhan;
			}
			set
			{
				if ((this._Id_TinNhan != value))
				{
					this.OnId_TinNhanChanging(value);
					this.SendPropertyChanging();
					this._Id_TinNhan = value;
					this.SendPropertyChanged("Id_TinNhan");
					this.OnId_TinNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_NguoiGui", DbType="Int")]
		public System.Nullable<int> Id_NguoiGui
		{
			get
			{
				return this._Id_NguoiGui;
			}
			set
			{
				if ((this._Id_NguoiGui != value))
				{
					this.OnId_NguoiGuiChanging(value);
					this.SendPropertyChanging();
					this._Id_NguoiGui = value;
					this.SendPropertyChanged("Id_NguoiGui");
					this.OnId_NguoiGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_NguoiNhan", DbType="Int")]
		public System.Nullable<int> Id_NguoiNhan
		{
			get
			{
				return this._Id_NguoiNhan;
			}
			set
			{
				if ((this._Id_NguoiNhan != value))
				{
					this.OnId_NguoiNhanChanging(value);
					this.SendPropertyChanging();
					this._Id_NguoiNhan = value;
					this.SendPropertyChanged("Id_NguoiNhan");
					this.OnId_NguoiNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGui", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayGui
		{
			get
			{
				return this._NgayGui;
			}
			set
			{
				if ((this._NgayGui != value))
				{
					this.OnNgayGuiChanging(value);
					this.SendPropertyChanging();
					this._NgayGui = value;
					this.SendPropertyChanged("NgayGui");
					this.OnNgayGuiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ANN")]
	public partial class ANN
	{
		
		private System.Nullable<int> _Id_Game;
		
		private int _Id_Anh;
		
		private string _Link;
		
		public ANN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Game", DbType="Int")]
		public System.Nullable<int> Id_Game
		{
			get
			{
				return this._Id_Game;
			}
			set
			{
				if ((this._Id_Game != value))
				{
					this._Id_Game = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Anh", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id_Anh
		{
			get
			{
				return this._Id_Anh;
			}
			set
			{
				if ((this._Id_Anh != value))
				{
					this._Id_Anh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="VarChar(255)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this._Link = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BAIDANGCONGDONG")]
	public partial class BAIDANGCONGDONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_BaiDang;
		
		private System.Nullable<int> _Id_NguoiDang;
		
		private string _TieuDe;
		
		private string _NoiDung;
		
		private string _HinhAnh;
		
		private string _Video;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private System.Nullable<bool> _KiemDuyet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_BaiDangChanging(int value);
    partial void OnId_BaiDangChanged();
    partial void OnId_NguoiDangChanging(System.Nullable<int> value);
    partial void OnId_NguoiDangChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnVideoChanging(string value);
    partial void OnVideoChanged();
    partial void OnNgayDangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangChanged();
    partial void OnKiemDuyetChanging(System.Nullable<bool> value);
    partial void OnKiemDuyetChanged();
    #endregion
		
		public BAIDANGCONGDONG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_BaiDang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_BaiDang
		{
			get
			{
				return this._Id_BaiDang;
			}
			set
			{
				if ((this._Id_BaiDang != value))
				{
					this.OnId_BaiDangChanging(value);
					this.SendPropertyChanging();
					this._Id_BaiDang = value;
					this.SendPropertyChanged("Id_BaiDang");
					this.OnId_BaiDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_NguoiDang", DbType="Int")]
		public System.Nullable<int> Id_NguoiDang
		{
			get
			{
				return this._Id_NguoiDang;
			}
			set
			{
				if ((this._Id_NguoiDang != value))
				{
					this.OnId_NguoiDangChanging(value);
					this.SendPropertyChanging();
					this._Id_NguoiDang = value;
					this.SendPropertyChanged("Id_NguoiDang");
					this.OnId_NguoiDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="VarChar(255)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Video", DbType="VarChar(255)")]
		public string Video
		{
			get
			{
				return this._Video;
			}
			set
			{
				if ((this._Video != value))
				{
					this.OnVideoChanging(value);
					this.SendPropertyChanging();
					this._Video = value;
					this.SendPropertyChanged("Video");
					this.OnVideoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this.OnNgayDangChanging(value);
					this.SendPropertyChanging();
					this._NgayDang = value;
					this.SendPropertyChanged("NgayDang");
					this.OnNgayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KiemDuyet", DbType="Bit")]
		public System.Nullable<bool> KiemDuyet
		{
			get
			{
				return this._KiemDuyet;
			}
			set
			{
				if ((this._KiemDuyet != value))
				{
					this.OnKiemDuyetChanging(value);
					this.SendPropertyChanging();
					this._KiemDuyet = value;
					this.SendPropertyChanged("KiemDuyet");
					this.OnKiemDuyetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETDONHANG")]
	public partial class CHITIETDONHANG
	{
		
		private System.Nullable<int> _Id_DonHang;
		
		private System.Nullable<int> _Id_Game;
		
		public CHITIETDONHANG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_DonHang", DbType="Int")]
		public System.Nullable<int> Id_DonHang
		{
			get
			{
				return this._Id_DonHang;
			}
			set
			{
				if ((this._Id_DonHang != value))
				{
					this._Id_DonHang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Game", DbType="Int")]
		public System.Nullable<int> Id_Game
		{
			get
			{
				return this._Id_Game;
			}
			set
			{
				if ((this._Id_Game != value))
				{
					this._Id_Game = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANHGIA")]
	public partial class DANHGIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_DanhGia;
		
		private System.Nullable<int> _Id_Game;
		
		private System.Nullable<int> _Id_KH;
		
		private string _BinhLuan;
		
		private System.Nullable<int> _DanhGia1;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_DanhGiaChanging(int value);
    partial void OnId_DanhGiaChanged();
    partial void OnId_GameChanging(System.Nullable<int> value);
    partial void OnId_GameChanged();
    partial void OnId_KHChanging(System.Nullable<int> value);
    partial void OnId_KHChanged();
    partial void OnBinhLuanChanging(string value);
    partial void OnBinhLuanChanged();
    partial void OnDanhGia1Changing(System.Nullable<int> value);
    partial void OnDanhGia1Changed();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    #endregion
		
		public DANHGIA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_DanhGia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_DanhGia
		{
			get
			{
				return this._Id_DanhGia;
			}
			set
			{
				if ((this._Id_DanhGia != value))
				{
					this.OnId_DanhGiaChanging(value);
					this.SendPropertyChanging();
					this._Id_DanhGia = value;
					this.SendPropertyChanged("Id_DanhGia");
					this.OnId_DanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Game", DbType="Int")]
		public System.Nullable<int> Id_Game
		{
			get
			{
				return this._Id_Game;
			}
			set
			{
				if ((this._Id_Game != value))
				{
					this.OnId_GameChanging(value);
					this.SendPropertyChanging();
					this._Id_Game = value;
					this.SendPropertyChanged("Id_Game");
					this.OnId_GameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_KH", DbType="Int")]
		public System.Nullable<int> Id_KH
		{
			get
			{
				return this._Id_KH;
			}
			set
			{
				if ((this._Id_KH != value))
				{
					this.OnId_KHChanging(value);
					this.SendPropertyChanging();
					this._Id_KH = value;
					this.SendPropertyChanged("Id_KH");
					this.OnId_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BinhLuan", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string BinhLuan
		{
			get
			{
				return this._BinhLuan;
			}
			set
			{
				if ((this._BinhLuan != value))
				{
					this.OnBinhLuanChanging(value);
					this.SendPropertyChanging();
					this._BinhLuan = value;
					this.SendPropertyChanged("BinhLuan");
					this.OnBinhLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="DanhGia", Storage="_DanhGia1", DbType="Int")]
		public System.Nullable<int> DanhGia1
		{
			get
			{
				return this._DanhGia1;
			}
			set
			{
				if ((this._DanhGia1 != value))
				{
					this.OnDanhGia1Changing(value);
					this.SendPropertyChanging();
					this._DanhGia1 = value;
					this.SendPropertyChanged("DanhGia1");
					this.OnDanhGia1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANHGIACONGDONG")]
	public partial class DANHGIACONGDONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_DanhGiaCD;
		
		private System.Nullable<int> _Id_BaiDang;
		
		private System.Nullable<int> _Id_KH;
		
		private string _BinhLuan;
		
		private System.Nullable<int> _DanhGia;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_DanhGiaCDChanging(int value);
    partial void OnId_DanhGiaCDChanged();
    partial void OnId_BaiDangChanging(System.Nullable<int> value);
    partial void OnId_BaiDangChanged();
    partial void OnId_KHChanging(System.Nullable<int> value);
    partial void OnId_KHChanged();
    partial void OnBinhLuanChanging(string value);
    partial void OnBinhLuanChanged();
    partial void OnDanhGiaChanging(System.Nullable<int> value);
    partial void OnDanhGiaChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    #endregion
		
		public DANHGIACONGDONG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_DanhGiaCD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_DanhGiaCD
		{
			get
			{
				return this._Id_DanhGiaCD;
			}
			set
			{
				if ((this._Id_DanhGiaCD != value))
				{
					this.OnId_DanhGiaCDChanging(value);
					this.SendPropertyChanging();
					this._Id_DanhGiaCD = value;
					this.SendPropertyChanged("Id_DanhGiaCD");
					this.OnId_DanhGiaCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_BaiDang", DbType="Int")]
		public System.Nullable<int> Id_BaiDang
		{
			get
			{
				return this._Id_BaiDang;
			}
			set
			{
				if ((this._Id_BaiDang != value))
				{
					this.OnId_BaiDangChanging(value);
					this.SendPropertyChanging();
					this._Id_BaiDang = value;
					this.SendPropertyChanged("Id_BaiDang");
					this.OnId_BaiDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_KH", DbType="Int")]
		public System.Nullable<int> Id_KH
		{
			get
			{
				return this._Id_KH;
			}
			set
			{
				if ((this._Id_KH != value))
				{
					this.OnId_KHChanging(value);
					this.SendPropertyChanging();
					this._Id_KH = value;
					this.SendPropertyChanged("Id_KH");
					this.OnId_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BinhLuan", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string BinhLuan
		{
			get
			{
				return this._BinhLuan;
			}
			set
			{
				if ((this._BinhLuan != value))
				{
					this.OnBinhLuanChanging(value);
					this.SendPropertyChanging();
					this._BinhLuan = value;
					this.SendPropertyChanged("BinhLuan");
					this.OnBinhLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhGia", DbType="Int")]
		public System.Nullable<int> DanhGia
		{
			get
			{
				return this._DanhGia;
			}
			set
			{
				if ((this._DanhGia != value))
				{
					this.OnDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._DanhGia = value;
					this.SendPropertyChanged("DanhGia");
					this.OnDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONHANG")]
	public partial class DONHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_DonHang;
		
		private System.Nullable<int> _Id_KH;
		
		private System.Nullable<System.DateTime> _NgayMua;
		
		private System.Nullable<bool> _TinhTrang;
		
		private System.Nullable<int> _Id_PTThanhToan;
		
		private System.Nullable<decimal> _TongTien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_DonHangChanging(int value);
    partial void OnId_DonHangChanged();
    partial void OnId_KHChanging(System.Nullable<int> value);
    partial void OnId_KHChanged();
    partial void OnNgayMuaChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayMuaChanged();
    partial void OnTinhTrangChanging(System.Nullable<bool> value);
    partial void OnTinhTrangChanged();
    partial void OnId_PTThanhToanChanging(System.Nullable<int> value);
    partial void OnId_PTThanhToanChanged();
    partial void OnTongTienChanging(System.Nullable<decimal> value);
    partial void OnTongTienChanged();
    #endregion
		
		public DONHANG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_DonHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_DonHang
		{
			get
			{
				return this._Id_DonHang;
			}
			set
			{
				if ((this._Id_DonHang != value))
				{
					this.OnId_DonHangChanging(value);
					this.SendPropertyChanging();
					this._Id_DonHang = value;
					this.SendPropertyChanged("Id_DonHang");
					this.OnId_DonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_KH", DbType="Int")]
		public System.Nullable<int> Id_KH
		{
			get
			{
				return this._Id_KH;
			}
			set
			{
				if ((this._Id_KH != value))
				{
					this.OnId_KHChanging(value);
					this.SendPropertyChanging();
					this._Id_KH = value;
					this.SendPropertyChanged("Id_KH");
					this.OnId_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMua", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayMua
		{
			get
			{
				return this._NgayMua;
			}
			set
			{
				if ((this._NgayMua != value))
				{
					this.OnNgayMuaChanging(value);
					this.SendPropertyChanging();
					this._NgayMua = value;
					this.SendPropertyChanged("NgayMua");
					this.OnNgayMuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Bit")]
		public System.Nullable<bool> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_PTThanhToan", DbType="Int")]
		public System.Nullable<int> Id_PTThanhToan
		{
			get
			{
				return this._Id_PTThanhToan;
			}
			set
			{
				if ((this._Id_PTThanhToan != value))
				{
					this.OnId_PTThanhToanChanging(value);
					this.SendPropertyChanging();
					this._Id_PTThanhToan = value;
					this.SendPropertyChanged("Id_PTThanhToan");
					this.OnId_PTThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Money")]
		public System.Nullable<decimal> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GAME_THELOAI")]
	public partial class GAME_THELOAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_GTTL;
		
		private System.Nullable<int> _Id_Game;
		
		private System.Nullable<int> _Id_TheLoai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_GTTLChanging(int value);
    partial void OnId_GTTLChanged();
    partial void OnId_GameChanging(System.Nullable<int> value);
    partial void OnId_GameChanged();
    partial void OnId_TheLoaiChanging(System.Nullable<int> value);
    partial void OnId_TheLoaiChanged();
    #endregion
		
		public GAME_THELOAI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_GTTL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_GTTL
		{
			get
			{
				return this._Id_GTTL;
			}
			set
			{
				if ((this._Id_GTTL != value))
				{
					this.OnId_GTTLChanging(value);
					this.SendPropertyChanging();
					this._Id_GTTL = value;
					this.SendPropertyChanged("Id_GTTL");
					this.OnId_GTTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Game", DbType="Int")]
		public System.Nullable<int> Id_Game
		{
			get
			{
				return this._Id_Game;
			}
			set
			{
				if ((this._Id_Game != value))
				{
					this.OnId_GameChanging(value);
					this.SendPropertyChanging();
					this._Id_Game = value;
					this.SendPropertyChanged("Id_Game");
					this.OnId_GameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_TheLoai", DbType="Int")]
		public System.Nullable<int> Id_TheLoai
		{
			get
			{
				return this._Id_TheLoai;
			}
			set
			{
				if ((this._Id_TheLoai != value))
				{
					this.OnId_TheLoaiChanging(value);
					this.SendPropertyChanging();
					this._Id_TheLoai = value;
					this.SendPropertyChanged("Id_TheLoai");
					this.OnId_TheLoaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GAMES")]
	public partial class GAME : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Game;
		
		private string _TenGame;
		
		private System.Nullable<int> _Id_NhaPhatHanh;
		
		private System.Nullable<int> _Id_NhaPhatTrien;
		
		private System.Nullable<int> _Id_TheLoai;
		
		private string _MoTa;
		
		private System.Nullable<int> _GioiHan_Tuoi;
		
		private System.Nullable<System.DateTime> _NgayPhatHanh;
		
		private System.Nullable<int> _Id_QuocGia;
		
		private System.Nullable<decimal> _Gia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_GameChanging(int value);
    partial void OnId_GameChanged();
    partial void OnTenGameChanging(string value);
    partial void OnTenGameChanged();
    partial void OnId_NhaPhatHanhChanging(System.Nullable<int> value);
    partial void OnId_NhaPhatHanhChanged();
    partial void OnId_NhaPhatTrienChanging(System.Nullable<int> value);
    partial void OnId_NhaPhatTrienChanged();
    partial void OnId_TheLoaiChanging(System.Nullable<int> value);
    partial void OnId_TheLoaiChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnGioiHan_TuoiChanging(System.Nullable<int> value);
    partial void OnGioiHan_TuoiChanged();
    partial void OnNgayPhatHanhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayPhatHanhChanged();
    partial void OnId_QuocGiaChanging(System.Nullable<int> value);
    partial void OnId_QuocGiaChanged();
    partial void OnGiaChanging(System.Nullable<decimal> value);
    partial void OnGiaChanged();
    #endregion
		
		public GAME()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Game", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Game
		{
			get
			{
				return this._Id_Game;
			}
			set
			{
				if ((this._Id_Game != value))
				{
					this.OnId_GameChanging(value);
					this.SendPropertyChanging();
					this._Id_Game = value;
					this.SendPropertyChanged("Id_Game");
					this.OnId_GameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGame", DbType="NVarChar(100)")]
		public string TenGame
		{
			get
			{
				return this._TenGame;
			}
			set
			{
				if ((this._TenGame != value))
				{
					this.OnTenGameChanging(value);
					this.SendPropertyChanging();
					this._TenGame = value;
					this.SendPropertyChanged("TenGame");
					this.OnTenGameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_NhaPhatHanh", DbType="Int")]
		public System.Nullable<int> Id_NhaPhatHanh
		{
			get
			{
				return this._Id_NhaPhatHanh;
			}
			set
			{
				if ((this._Id_NhaPhatHanh != value))
				{
					this.OnId_NhaPhatHanhChanging(value);
					this.SendPropertyChanging();
					this._Id_NhaPhatHanh = value;
					this.SendPropertyChanged("Id_NhaPhatHanh");
					this.OnId_NhaPhatHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_NhaPhatTrien", DbType="Int")]
		public System.Nullable<int> Id_NhaPhatTrien
		{
			get
			{
				return this._Id_NhaPhatTrien;
			}
			set
			{
				if ((this._Id_NhaPhatTrien != value))
				{
					this.OnId_NhaPhatTrienChanging(value);
					this.SendPropertyChanging();
					this._Id_NhaPhatTrien = value;
					this.SendPropertyChanged("Id_NhaPhatTrien");
					this.OnId_NhaPhatTrienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_TheLoai", DbType="Int")]
		public System.Nullable<int> Id_TheLoai
		{
			get
			{
				return this._Id_TheLoai;
			}
			set
			{
				if ((this._Id_TheLoai != value))
				{
					this.OnId_TheLoaiChanging(value);
					this.SendPropertyChanging();
					this._Id_TheLoai = value;
					this.SendPropertyChanged("Id_TheLoai");
					this.OnId_TheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiHan_Tuoi", DbType="Int")]
		public System.Nullable<int> GioiHan_Tuoi
		{
			get
			{
				return this._GioiHan_Tuoi;
			}
			set
			{
				if ((this._GioiHan_Tuoi != value))
				{
					this.OnGioiHan_TuoiChanging(value);
					this.SendPropertyChanging();
					this._GioiHan_Tuoi = value;
					this.SendPropertyChanged("GioiHan_Tuoi");
					this.OnGioiHan_TuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayPhatHanh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayPhatHanh
		{
			get
			{
				return this._NgayPhatHanh;
			}
			set
			{
				if ((this._NgayPhatHanh != value))
				{
					this.OnNgayPhatHanhChanging(value);
					this.SendPropertyChanging();
					this._NgayPhatHanh = value;
					this.SendPropertyChanged("NgayPhatHanh");
					this.OnNgayPhatHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_QuocGia", DbType="Int")]
		public System.Nullable<int> Id_QuocGia
		{
			get
			{
				return this._Id_QuocGia;
			}
			set
			{
				if ((this._Id_QuocGia != value))
				{
					this.OnId_QuocGiaChanging(value);
					this.SendPropertyChanging();
					this._Id_QuocGia = value;
					this.SendPropertyChanged("Id_QuocGia");
					this.OnId_QuocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Money")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KETBAN")]
	public partial class KETBAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_KetBan;
		
		private System.Nullable<int> _Id_NguoiGui;
		
		private System.Nullable<int> _Id_NguoiNhan;
		
		private System.Nullable<System.DateTime> _NgayKetBan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_KetBanChanging(int value);
    partial void OnId_KetBanChanged();
    partial void OnId_NguoiGuiChanging(System.Nullable<int> value);
    partial void OnId_NguoiGuiChanged();
    partial void OnId_NguoiNhanChanging(System.Nullable<int> value);
    partial void OnId_NguoiNhanChanged();
    partial void OnNgayKetBanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKetBanChanged();
    #endregion
		
		public KETBAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_KetBan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_KetBan
		{
			get
			{
				return this._Id_KetBan;
			}
			set
			{
				if ((this._Id_KetBan != value))
				{
					this.OnId_KetBanChanging(value);
					this.SendPropertyChanging();
					this._Id_KetBan = value;
					this.SendPropertyChanged("Id_KetBan");
					this.OnId_KetBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_NguoiGui", DbType="Int")]
		public System.Nullable<int> Id_NguoiGui
		{
			get
			{
				return this._Id_NguoiGui;
			}
			set
			{
				if ((this._Id_NguoiGui != value))
				{
					this.OnId_NguoiGuiChanging(value);
					this.SendPropertyChanging();
					this._Id_NguoiGui = value;
					this.SendPropertyChanged("Id_NguoiGui");
					this.OnId_NguoiGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_NguoiNhan", DbType="Int")]
		public System.Nullable<int> Id_NguoiNhan
		{
			get
			{
				return this._Id_NguoiNhan;
			}
			set
			{
				if ((this._Id_NguoiNhan != value))
				{
					this.OnId_NguoiNhanChanging(value);
					this.SendPropertyChanging();
					this._Id_NguoiNhan = value;
					this.SendPropertyChanged("Id_NguoiNhan");
					this.OnId_NguoiNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetBan", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayKetBan
		{
			get
			{
				return this._NgayKetBan;
			}
			set
			{
				if ((this._NgayKetBan != value))
				{
					this.OnNgayKetBanChanging(value);
					this.SendPropertyChanging();
					this._NgayKetBan = value;
					this.SendPropertyChanged("NgayKetBan");
					this.OnNgayKetBanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _HoTen;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _Email;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    #endregion
		
		public KHACHHANG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(15)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(15)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(10)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHAPHATHANH")]
	public partial class NHAPHATHANH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_NhaPhatHanh;
		
		private string _TenNhaPhatHanh;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private string _Email;
		
		private string _Website;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_NhaPhatHanhChanging(int value);
    partial void OnId_NhaPhatHanhChanged();
    partial void OnTenNhaPhatHanhChanging(string value);
    partial void OnTenNhaPhatHanhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnWebsiteChanging(string value);
    partial void OnWebsiteChanged();
    #endregion
		
		public NHAPHATHANH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_NhaPhatHanh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_NhaPhatHanh
		{
			get
			{
				return this._Id_NhaPhatHanh;
			}
			set
			{
				if ((this._Id_NhaPhatHanh != value))
				{
					this.OnId_NhaPhatHanhChanging(value);
					this.SendPropertyChanging();
					this._Id_NhaPhatHanh = value;
					this.SendPropertyChanged("Id_NhaPhatHanh");
					this.OnId_NhaPhatHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhaPhatHanh", DbType="NVarChar(255)")]
		public string TenNhaPhatHanh
		{
			get
			{
				return this._TenNhaPhatHanh;
			}
			set
			{
				if ((this._TenNhaPhatHanh != value))
				{
					this.OnTenNhaPhatHanhChanging(value);
					this.SendPropertyChanging();
					this._TenNhaPhatHanh = value;
					this.SendPropertyChanged("TenNhaPhatHanh");
					this.OnTenNhaPhatHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(255)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(20)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="VarChar(255)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this.OnWebsiteChanging(value);
					this.SendPropertyChanging();
					this._Website = value;
					this.SendPropertyChanged("Website");
					this.OnWebsiteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHAPHATTRIEN")]
	public partial class NHAPHATTRIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_NhaPhatTrien;
		
		private string _TenNhaPhatTrien;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private string _Email;
		
		private string _Website;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_NhaPhatTrienChanging(int value);
    partial void OnId_NhaPhatTrienChanged();
    partial void OnTenNhaPhatTrienChanging(string value);
    partial void OnTenNhaPhatTrienChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnWebsiteChanging(string value);
    partial void OnWebsiteChanged();
    #endregion
		
		public NHAPHATTRIEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_NhaPhatTrien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_NhaPhatTrien
		{
			get
			{
				return this._Id_NhaPhatTrien;
			}
			set
			{
				if ((this._Id_NhaPhatTrien != value))
				{
					this.OnId_NhaPhatTrienChanging(value);
					this.SendPropertyChanging();
					this._Id_NhaPhatTrien = value;
					this.SendPropertyChanged("Id_NhaPhatTrien");
					this.OnId_NhaPhatTrienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhaPhatTrien", DbType="NVarChar(255)")]
		public string TenNhaPhatTrien
		{
			get
			{
				return this._TenNhaPhatTrien;
			}
			set
			{
				if ((this._TenNhaPhatTrien != value))
				{
					this.OnTenNhaPhatTrienChanging(value);
					this.SendPropertyChanging();
					this._TenNhaPhatTrien = value;
					this.SendPropertyChanged("TenNhaPhatTrien");
					this.OnTenNhaPhatTrienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(255)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(20)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="VarChar(255)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this.OnWebsiteChanging(value);
					this.SendPropertyChanging();
					this._Website = value;
					this.SendPropertyChanged("Website");
					this.OnWebsiteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PTTHANHTOAN")]
	public partial class PTTHANHTOAN
	{
		
		private int _Id_PTThanhToan;
		
		private string _Ten_PTThanhToan;
		
		public PTTHANHTOAN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_PTThanhToan", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id_PTThanhToan
		{
			get
			{
				return this._Id_PTThanhToan;
			}
			set
			{
				if ((this._Id_PTThanhToan != value))
				{
					this._Id_PTThanhToan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_PTThanhToan", DbType="NVarChar(255)")]
		public string Ten_PTThanhToan
		{
			get
			{
				return this._Ten_PTThanhToan;
			}
			set
			{
				if ((this._Ten_PTThanhToan != value))
				{
					this._Ten_PTThanhToan = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUOCGIA")]
	public partial class QUOCGIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_QuocGia;
		
		private string _TenQuocGia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_QuocGiaChanging(int value);
    partial void OnId_QuocGiaChanged();
    partial void OnTenQuocGiaChanging(string value);
    partial void OnTenQuocGiaChanged();
    #endregion
		
		public QUOCGIA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_QuocGia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_QuocGia
		{
			get
			{
				return this._Id_QuocGia;
			}
			set
			{
				if ((this._Id_QuocGia != value))
				{
					this.OnId_QuocGiaChanging(value);
					this.SendPropertyChanging();
					this._Id_QuocGia = value;
					this.SendPropertyChanged("Id_QuocGia");
					this.OnId_QuocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuocGia", DbType="NVarChar(255)")]
		public string TenQuocGia
		{
			get
			{
				return this._TenQuocGia;
			}
			set
			{
				if ((this._TenQuocGia != value))
				{
					this.OnTenQuocGiaChanging(value);
					this.SendPropertyChanging();
					this._TenQuocGia = value;
					this.SendPropertyChanged("TenQuocGia");
					this.OnTenQuocGiaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THELOAI")]
	public partial class THELOAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_TheLoai;
		
		private string _TenTheLoai;
		
		private string _MoTa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_TheLoaiChanging(int value);
    partial void OnId_TheLoaiChanged();
    partial void OnTenTheLoaiChanging(string value);
    partial void OnTenTheLoaiChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public THELOAI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_TheLoai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_TheLoai
		{
			get
			{
				return this._Id_TheLoai;
			}
			set
			{
				if ((this._Id_TheLoai != value))
				{
					this.OnId_TheLoaiChanging(value);
					this.SendPropertyChanging();
					this._Id_TheLoai = value;
					this.SendPropertyChanged("Id_TheLoai");
					this.OnId_TheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTheLoai", DbType="NVarChar(255)")]
		public string TenTheLoai
		{
			get
			{
				return this._TenTheLoai;
			}
			set
			{
				if ((this._TenTheLoai != value))
				{
					this.OnTenTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenTheLoai = value;
					this.SendPropertyChanged("TenTheLoai");
					this.OnTenTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KETBAN")]
	public partial class KETBAN1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_KetBan;
		
		private System.Nullable<int> _Id_NguoiGui;
		
		private System.Nullable<int> _Id_NguoiNhan;
		
		private System.Nullable<System.DateTime> _NgayKetBan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_KetBanChanging(int value);
    partial void OnId_KetBanChanged();
    partial void OnId_NguoiGuiChanging(System.Nullable<int> value);
    partial void OnId_NguoiGuiChanged();
    partial void OnId_NguoiNhanChanging(System.Nullable<int> value);
    partial void OnId_NguoiNhanChanged();
    partial void OnNgayKetBanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKetBanChanged();
    #endregion
		
		public KETBAN1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_KetBan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_KetBan
		{
			get
			{
				return this._Id_KetBan;
			}
			set
			{
				if ((this._Id_KetBan != value))
				{
					this.OnId_KetBanChanging(value);
					this.SendPropertyChanging();
					this._Id_KetBan = value;
					this.SendPropertyChanged("Id_KetBan");
					this.OnId_KetBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_NguoiGui", DbType="Int")]
		public System.Nullable<int> Id_NguoiGui
		{
			get
			{
				return this._Id_NguoiGui;
			}
			set
			{
				if ((this._Id_NguoiGui != value))
				{
					this.OnId_NguoiGuiChanging(value);
					this.SendPropertyChanging();
					this._Id_NguoiGui = value;
					this.SendPropertyChanged("Id_NguoiGui");
					this.OnId_NguoiGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_NguoiNhan", DbType="Int")]
		public System.Nullable<int> Id_NguoiNhan
		{
			get
			{
				return this._Id_NguoiNhan;
			}
			set
			{
				if ((this._Id_NguoiNhan != value))
				{
					this.OnId_NguoiNhanChanging(value);
					this.SendPropertyChanging();
					this._Id_NguoiNhan = value;
					this.SendPropertyChanged("Id_NguoiNhan");
					this.OnId_NguoiNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetBan", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayKetBan
		{
			get
			{
				return this._NgayKetBan;
			}
			set
			{
				if ((this._NgayKetBan != value))
				{
					this.OnNgayKetBanChanging(value);
					this.SendPropertyChanging();
					this._NgayKetBan = value;
					this.SendPropertyChanged("NgayKetBan");
					this.OnNgayKetBanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
