#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="webgame")]
	public partial class DataGameStoreDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataGameStoreDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["webgameConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataGameStoreDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataGameStoreDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataGameStoreDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataGameStoreDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Menu> Menus
		{
			get
			{
				return this.GetTable<Menu>();
			}
		}
		
		public System.Data.Linq.Table<Game> Games
		{
			get
			{
				return this.GetTable<Game>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menu")]
	public partial class Menu
	{
		
		private System.Nullable<int> _id;
		
		private string _TenMN;
		
		public Menu()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMN", DbType="NVarChar(50)")]
		public string TenMN
		{
			get
			{
				return this._TenMN;
			}
			set
			{
				if ((this._TenMN != value))
				{
					this._TenMN = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Game")]
	public partial class Game
	{
		
		private int _id;
		
		private string _nameGame;
		
		private string _imgName;
		
		private string _listImage;
		
		private string _attGame;
		
		private string _tagGame;
		
		private string _typeGame;
		
		private string _devsGame;
		
		private string _publisher;
		
		private System.Nullable<int> _priceGame;
		
		private string _desGame;
		
		private System.Nullable<int> _yearRelease;
		
		private string _requireGame;
		
		private System.Nullable<bool> _enableGame;
		
		private System.Nullable<System.DateTime> _dateModified;
		
		public Game()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameGame", DbType="NVarChar(500)")]
		public string nameGame
		{
			get
			{
				return this._nameGame;
			}
			set
			{
				if ((this._nameGame != value))
				{
					this._nameGame = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgName", DbType="NVarChar(500)")]
		public string imgName
		{
			get
			{
				return this._imgName;
			}
			set
			{
				if ((this._imgName != value))
				{
					this._imgName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_listImage", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string listImage
		{
			get
			{
				return this._listImage;
			}
			set
			{
				if ((this._listImage != value))
				{
					this._listImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attGame", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string attGame
		{
			get
			{
				return this._attGame;
			}
			set
			{
				if ((this._attGame != value))
				{
					this._attGame = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tagGame", DbType="NVarChar(1000)")]
		public string tagGame
		{
			get
			{
				return this._tagGame;
			}
			set
			{
				if ((this._tagGame != value))
				{
					this._tagGame = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeGame", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string typeGame
		{
			get
			{
				return this._typeGame;
			}
			set
			{
				if ((this._typeGame != value))
				{
					this._typeGame = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_devsGame", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string devsGame
		{
			get
			{
				return this._devsGame;
			}
			set
			{
				if ((this._devsGame != value))
				{
					this._devsGame = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publisher", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string publisher
		{
			get
			{
				return this._publisher;
			}
			set
			{
				if ((this._publisher != value))
				{
					this._publisher = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priceGame", DbType="Int")]
		public System.Nullable<int> priceGame
		{
			get
			{
				return this._priceGame;
			}
			set
			{
				if ((this._priceGame != value))
				{
					this._priceGame = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desGame", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string desGame
		{
			get
			{
				return this._desGame;
			}
			set
			{
				if ((this._desGame != value))
				{
					this._desGame = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yearRelease", DbType="Int")]
		public System.Nullable<int> yearRelease
		{
			get
			{
				return this._yearRelease;
			}
			set
			{
				if ((this._yearRelease != value))
				{
					this._yearRelease = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_requireGame", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string requireGame
		{
			get
			{
				return this._requireGame;
			}
			set
			{
				if ((this._requireGame != value))
				{
					this._requireGame = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enableGame", DbType="Bit")]
		public System.Nullable<bool> enableGame
		{
			get
			{
				return this._enableGame;
			}
			set
			{
				if ((this._enableGame != value))
				{
					this._enableGame = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateModified", DbType="Date")]
		public System.Nullable<System.DateTime> dateModified
		{
			get
			{
				return this._dateModified;
			}
			set
			{
				if ((this._dateModified != value))
				{
					this._dateModified = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
